### PR TITLE
Custom validate function

### LINKED ISSUE #18: Allow implementors to provide their own `validate()` function
The `validate()` function that's provided only allows for a very specific timestamp format, specifically timestamps with leading zeroes. It would be great if a `validate={}` prop could be passed that would allow the implementor to provide their own validator.

### PR DESCRIPTION
**Pull request by mattbasta**
Resolves #18 

In order to make this work, I had to bump the `react-dom` and `react-addons-test-utils`; the tests will fail without those because React 15.4.0 changes `react-addons-test-utils` to depend on `react-dom` 15.4.

Please let me know if there are any changes that need to be made.

### CODE REVIEW

**Comment by alanclarke** [comment]
@mattbasta thanks so much for this pr and for the issue explaining the rationale. I think this may be a bit more tricky that the pr suggests since the validate function is really internal logic and the rest of the codebase relies on things like time groups being at certain indexes.

In its current form we shouldn't expose this validate function, but maybe we could just implement the feature you're after and have a no leading zeros option?

**Comment by Murriouz** [comment]
I think custom validate function is very helpful.
In my case, the limit of the time input should be 59:59:59, but in this component it's hardcoded to 23:59:59. Or maybe there's other way to change the limit. Thanks.

**Comment by alanclarke** [comment]
@Murriouz i understand, however this is more involved than this pr suggests - we're assuming a standard time format throughout the codebase, so would need to factor that in. e.g. see https://github.com/alanclarke/time-input/blob/master/src/lib/get-base.js

**Comment by alanclarke** [comment]
formatting requirement covered here: #21

**Pull request closed without merging**
